#
# Inspired by:
#   - 'esp-hal-template'
#     -> https://github.com/jessebraham/esp-hal-template/blob/main/embassy/.cargo/config.toml
#
#[env]
#DEFMT_LOG="debug"
#    # Note: You can give different logging levels to different Rust modules.
#    #       See -> https://defmt.ferrous-systems.com/filtering

[build]
# RISC V
rustflags = [
    # Required to obtain backtraces, however it may negatively impact the performance of your application.
    "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core"]
