#
# Inspired by:
#   - 'esp-hal-template'
#     -> https://github.com/jessebraham/esp-hal-template/blob/main/embassy/.cargo/config.toml
#

[build]
# RISC V
rustflags = [
    # Required to obtain backtraces, however it may negatively impact the performance of your application.
    "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core"]
