[package]
name = "vl53l5cx_uld"   # name matters; shows in the parent 'Cargo.toml'
edition = "2021"
publish = false

[dependencies]
defmt = "0.3.8"

[dev-dependencies]
assert_cfg = "0.1.0"    # used in samples
defmt-rtt = "0.4.1"

#Resp-println      = { version = "0.10.0", default-features = false, features = ["defmt-espflash", "jtag-serial"
#R    , "esp32c3"     # IF using other chip, change here (tbd. any better way to do it?  Makefile + env.vars?
#R                    # Don't want to introduce mcu-specific 'feature' if the actual code doesn't use them.
#R] }    # + {mcu}

[build-dependencies]
itertools = "0.13.0"

# C compile-time features
#
# Note: The names reflect the C side #define's (except for being lower case)
#
# Features define what fields are available in the ranging output. They actually drive the C library compilation.
# More fields means more I2C comms and more code size, so you will benefit from keeping the list tight.
#
# NOTE:
#   Some features are connected to others. We check this in 'build.rs'.
#
[features]
ambient_per_spad=[]     # VL53L5CX_DISABLE_AMBIENT_PER_SPAD
nb_spads_enabled=[]     # VL53L5CX_DISABLE_NB_SPADS_ENABLED
signal_per_spad=[]      # VL53L5CX_DISABLE_SIGNAL_PER_SPAD
range_sigma_mm=[]       # VL53L5CX_DISABLE_RANGE_SIGMA_MM
distance_mm=[]          # VL53L5CX_DISABLE_DISTANCE_MM
reflectance_percent=[]  # VL53L5CX_DISABLE_REFLECTANCE_PERCENT
motion_indicator=[]     # VL53L5CX_DISABLE_MOTION_INDICATOR

#nb_target_detected=[]   # VL53L5CX_DISABLE_NB_TARGET_DETECTED   // recommended by vendor docs
#target_status=[]        # VL53L5CX_DISABLE_TARGET_STATUS        // recommended by vendor docs

# Raw (firmware) format: raw numbers, "provides better accuracy".
use_raw_format=[]       # VL53L5CX_USE_RAW_FORMAT

targets_per_zone_1=[]
#targets_per_zone_2=[]
#targets_per_zone_3=[]
#targets_per_zone_4=[]

default = [
    "targets_per_zone_1"
]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(todo)', 'cfg(disabled)'] }
