#
# This Makefile is only for help - a wrapper around 'cargo build' to shorten the commands.
#
# Usage:
#	$ [DEFMT_LOG=trace|debug|info|...] [FEATURES=...] make -f Makefile.2 {m3|...}
#		# builds and runs a certain sample
#
DEFMT_LOG?=debug
FEATURES?=

LOG_ENV:=DEFMT_LOG=$(DEFMT_LOG)

DEFMT_HOST_FMT:='{t:dimmed} [{L:bold}] {s}'
DEFMT_FEATURES:=defmt

REMAKE:=$(MAKE) -f $(MAKEFILE_LIST)

# Read the 'TARGET' from './cargo/config.toml'
#
TARGET:=$(shell cat .cargo/config.toml | grep -e '^target\s*=\s"' | cut -d '"' -f2)
	# riscv32imac-unknown-none-elf

# Cargo 'target' path can be overridden
#
# - '.cargo/config.toml' > 'build.target-dir' in _any_ of the parent folders (!!!)
# - 'CARGO_BUILD_TARGET_DIR' and 'CARGO_TARGET_DIR' env.vars
#
# Overriding is EXTREMELY RECOMMENDED at least on Multipass VM (default is so in 'mp'). 13x SPEED IMPROVEMENT
# over mapping the files to host.
#
CARGO_TARGET_DIR:=target
	# tbd. detect the folder 'cargo' uses!!!

all:
	@false

# Note: Though trying in multiple ways, did not find a way to make 'cargo run --example' itself apply the 'defmt'
#		feature.

m3:
	EXAMPLE=m3 \
	  FEATURES=targets_per_zone_2,ambient_per_spad,nb_spads_enabled,signal_per_spad,range_sigma_mm,distance_mm,reflectance_percent \
	  $(REMAKE) --no-print-directory _build _run

#---
_build:
	$(LOG_ENV) cargo build --timings --release --features=$(FEATURES),$(DEFMT_FEATURES) --example $(EXAMPLE)

_run:
	probe-rs run --speed=200 --log-format $(DEFMT_HOST_FMT) $(CARGO_TARGET_DIR)/$(TARGET)/release/examples/$(EXAMPLE)

echo:
	@echo a

.PHONY: all m3 _build _run echo
