#pragma once

// Bit of a gamble, but..
//
// This is the place for centrally defining all the compile-time configs that matter for the
// 'vl53l5cx_api.c'.
//

//VL53L5CX_NB_TARGET_PER_ZONE
//VL53L5CX_DISABLE_AMBIENT_PER_SPAD
//VL53L5CX_DISABLE_NB_SPADS_ENABLED
//#define VL53L5CX_DISABLE_NB_TARGET_DETECTED
//VL53L5CX_DISABLE_SIGNAL_PER_SPAD
//VL53L5CX_DISABLE_RANGE_SIGMA_MM
//VL53L5CX_DISABLE_DISTANCE_MM
//VL53L5CX_DISABLE_REFLECTANCE_PERCENT
//VL53L5CX_DISABLE_TARGET_STATUS
//VL53L5CX_DISABLE_MOTION_INDICATOR
