#
# This Makefile is only for help - a wrapper around 'cargo build' to shorten the commands.
#
# Usage:
#	$ [DEFMT_LOG=trace|debug|info|...] [FEATURES=...] make -f Makefile.dev {flock|...}
#		# builds and runs a certain sample
#
DEFMT_LOG?=debug
FEATURES?=

LOG_ENV:=DEFMT_LOG=$(DEFMT_LOG)

DEFMT_HOST_FMT:='{t:dimmed} [{L:bold}] {s}'
DEFMT_FEATURES:=defmt

REMAKE:=$(MAKE) -f $(MAKEFILE_LIST)

# Read the 'TARGET' from './cargo/config.toml'
#
TARGET:=$(shell cat .cargo/config.toml | grep -e '^target\s*=\s"' | cut -d '"' -f2)
	# riscv32imac-unknown-none-elf

# Detect 'cargo' build cache
#
# 'cargo' stores output in a 'target' dir, but such is not necessary to keep in the project folder. [1]
#
#	[1]: Cargo Book > Build cache
#		https://doc.rust-lang.org/stable/cargo/guide/build-cache.html
#
# tbd. The right approach is likely to let 'cargo' runners handle this.
#
CARGO_TARGET_DIR:=target	# tbd. proper detection

all:
	@false

# Note: Though trying in multiple ways, did not find a way to make 'cargo run --example' itself apply the 'defmt'
#		feature.

flock z:
	EXAMPLE=flock \
	  FEATURES=distance_mm \
	  $(REMAKE) --no-print-directory _build _run

#---
_build:
	$(LOG_ENV) cargo build --release --features=$(FEATURES),$(DEFMT_FEATURES) --example $(EXAMPLE)

_run:
	probe-rs run --speed=200 --log-format $(DEFMT_HOST_FMT) $(CARGO_TARGET_DIR)/$(TARGET)/release/examples/$(EXAMPLE)

echo:
	@echo $(CARGO_TARGET_DIR)

.PHONY: all flock z _build _run echo
