#
# This Makefile is only for help - a wrapper around 'cargo build' to shorten the commands.
#
# Usage:
#	$ [DEFMT_LOG=trace|debug|info|...] [FEATURES=...] make -f Makefile.dev {abc|...}
#
DEFMT_LOG?=debug
FEATURES?=

LOG_ENV:=DEFMT_LOG=$(DEFMT_LOG)

REMAKE:=$(MAKE) -f $(MAKEFILE_LIST)

# Read the 'TARGET' from (nearest) '.cargo/config.toml'
#
TARGET:=$(shell cat ../.cargo/config.toml | grep -e '^target\s*=\s"' | cut -d '"' -f2)
	# riscv32imac-unknown-none-elf

# Detect the active MCU.
MCU:=$(shell cat Cargo.toml | grep -Eo -m 1 "esp32c[36]")
	# "esp32c3"|"esp32c6"

# ESP32-C3 needs PWM to be done using 'LEDC'; it has no dedicated Motor Control PWM (like the ESP32-C6 does).
ifneq ("esp32c3", "$(MCU)")
  FEATURES:=$(FEATURES),mcpwm
endif

all:
	@false

abc:
	EXAMPLE=abc \
	  FEATURES= \
	  $(REMAKE) --no-print-directory _build_run

#---
_build_run:
	$(LOG_ENV) cargo run --release --features=$(FEATURES) --example $(EXAMPLE)

echo:
	@echo $(MCU)

.PHONY: all abc _build_run echo
