#
# pins.toml
#
# Pins configuration for the project's examples. An include is generated, based on information in this file.
#
generate = "examples/pins-gen.in"

[boards.esp32c3]
IN1 = 6
IN2 = 7
BTN = 3

#[boards.esp32c6]
#IN1 = 6
#IN2 = 7
