#
# pins.toml
#
# Pins configuration for the project's examples. An include is generated, based on information in this file.
#
[boards.esp32c6]
SDA = 18
SCL = 19
PWR_EN = 21
INT = 22
LPn = [20, 23]

# Dev note:
#   - keep pins (other than LPn, which is unique here) the same as in the 'vl_uld' sister project, to avoid mistakes!!
