#[alias]
#esp32   = "run --release --features=esp32   --target=xtensa-esp32-none-elf"
#esp32c2 = "run --release --features=esp32c2 --target=riscv32imc-unknown-none-elf"
#esp32c3 = "run --release --features=esp32c3 --target=riscv32imc-unknown-none-elf"
#esp32c6 = "run --release --features=esp32c6 --target=riscv32imac-unknown-none-elf"
#esp32h2 = "run --release --features=esp32h2 --target=riscv32imac-unknown-none-elf"
#esp32s2 = "run --release --features=esp32s2 --target=xtensa-esp32s2-none-elf"
#esp32s3 = "run --release --features=esp32s3 --target=xtensa-esp32s3-none-elf"

#target = "riscv32imc-unknown-none-elf"  # C3, C2
#target = "riscv32iamc-unknown-none-elf"  # C6, H2

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "force-frame-pointers",
]

[env]
ESP_LOGLEVEL = "debug"

[unstable]
build-std = ["alloc", "core"]
