#
# pins.toml
#
# Pins configuration for the project's examples. An include is generated, based on information in this file.
#
generate = "examples/pins_gen.in"

[boards.esp32c6]
SDA = 18
SCL = 19
LPn = [20,21]
PWR_EN = 22
INT = 23
