#
# References:
#   - Cargo Book > Configuration
#       -> https://doc.rust-lang.org/cargo/reference/config.html
#
[build]
target = "riscv32imac-unknown-none-elf"      # change this by 'set-target.sh'

rustflags = [
    # Required to obtain backtraces, however it may negatively impact the performance of your application.
    #
    # Note: Interesting discussion in:
    #   - "`force-frame-pointers` flag isn't honored always unless std is recompiled as such"
    #       -> https://github.com/rust-lang/rust/issues/103711 (GitHub Issues; [closed])
    #
    # - [ ] Is there (really not) a way to provide this in 'build.rs' or 'Cargo.toml'?
    #
    "-C", "force-frame-pointers",
]

# Note: Cannot define a plane '[target]' - but we can bypass that by...
#
[target.'cfg(all())']   # this works; gives unconditional '[target]'
#runner = "probe-rs run --chip=esp32c6"
runner = "probe-rs run --chip=esp32c6 --log-format {L}_{s}"     # works (no space)
#runner = 'probe-rs run --chip=esp32c6 --log-format "{L} {s}"'
#        Running `probe-rs run --chip=esp32c6 --log-format '"{L}' '{s}"' target/riscv32imac-unknown-none-elf/release/examples/nada`
#           -> fails

    # Note: The author wasn't able to place a space in the '--log-format'. Tried:
    #       "[...] --log-format '{L} {s}'"
    #       "[...] --log-format \"{L} {s}\""
    #       '[...] --log-format "{L} {s}"'
    #       "[...] --log-format {L}\ {s}"
    #       '[...] --log-format {L}\ {s}'
