#
# References:
#   - Cargo Book > Configuration
#       -> https://doc.rust-lang.org/cargo/reference/config.html
#
[build]
target = "xtensa-esp32-none-elf"

# The bare minimums (from esp-template [1]) needed for ESP32.
#
#   [1]: https://github.com/esp-rs/esp-template/blob/main/.cargo/config.toml
#
rustflags = [
    "-C", "link-arg=-nostartfiles",     # for Xtensa (ESP32)
]

[target.'cfg(all())']   # unconditional '[target]' #hack
#runner = ["probe-rs", "run", "--log-format={L} {s}"]
runner = ["probe-rs", "run", "--log-format={[{L}]%bold} {s}  {{c} {ff}:{l:1}%dimmed}"]
    #
    # Note: Using the '[...]' format is the ONLY WAY that a space can be expressed in the '--log-format' syntax!
    #
    # Note: The author wasn't able to place a space in the '--log-format'. Tried:
    #       "[...] --log-format '{L} {s}'"
    #       "[...] --log-format \"{L} {s}\""
    #       '[...] --log-format "{L} {s}"'
    #       "[...] --log-format {L}\ {s}"
    #       '[...] --log-format {L}\ {s}'
    #       '[...] --log-format {L} {s}'    # NBSP
    #
    # For syntax, see -> https://defmt.ferrous-systems.com/custom-log-output#metadata-specifiers

# 'esp' toolchain uses these
[unstable]
gc = true
build-std = ["core"]    # needed for Xtensa 'no_std'
