// Generated by 'build.rs'
// DO NOT MAKE CHANGES HERE; THEY WILL GET LOST. Instead, edit 'pins.toml' and rebuild.
//
macro_rules! pins {
    ($peripherals:ident) => {{
        use esp_hal::gpio::Pin;

        // esp32c6.vl53l8
        Pins {
            SDA: $peripherals.GPIO20.into(),
            SCL: $peripherals.GPIO19.into(),
            PWR_EN: $peripherals.GPIO18.into(),
            INT: $peripherals.GPIO22.into(),
            #[cfg(feature="vl53l8cx")]
            SYNC: Some($peripherals.GPIO23.into()),
            LPn: [ Pin::degrade( $peripherals.GPIO21 ) ],
        }
    }}
}

#[allow(unused_macros)]
macro_rules! boards {
    () => {( 1 )}
}
